# Generated by Django 5.2.8 on 2025-11-19 00:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotillon_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
