# Generated by Django 5.2.8 on 2025-11-19 14:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotillon_api', '0002_alter_itemventa_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
