# Generated by Django 5.2.8 on 2025-11-21 17:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotillon_api', '0003_alter_itemventa_cantidad_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
    ]
